spring:
  profiles: local
  datasource:
      url: jdbc:mysql://101.43.205.43:3306/user_shiro?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: golaxy@6!
logging:
  config: classpath:logback-local.xml